import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/header";
import { cn } from "@/lib/utils";
import { Footer } from "@/components/layout/footer";
import { getAuthSession } from "@/actions/auth";
import { Toaster } from "@/components/ui/sonner";

const font = Poppins({
    weight: ["300", "400", "500", "600", "700", "800"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const authSession = await getAuthSession();
    return (
        <html lang="en">
            <body
                className={cn(font.className, "relative pt-20 text-gray-800")}
            >
                <Toaster theme="dark" richColors={true} position="top-center" />
                <Header authSession={authSession} />

                <main className="">{children}</main>

                <Footer />
            </body>
        </html>
    );
}
